=== siriusxiv/ubik/src/net/wastl/webmail/data/xml/sysdata.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT SYSDATA (VIRTUALS?, DOMAIN*, GROUP*)>
<!ELEMENT GROUP (CONFIG)*>
<!ELEMENT CONFIG (KEY, DESCRIPTION?, VALUE, CHOICE*)>
<!ELEMENT DESCRIPTION (#PCDATA)>
<!ELEMENT KEY (#PCDATA)>
<!ELEMENT VALUE (#PCDATA)>
<!ELEMENT CHOICE (#PCDATA)>
<!ELEMENT VIRTUALS EMPTY>

<!ELEMENT DOMAIN (NAME,DEFAULT_HOST,IMAP_BASEDIR?,AUTHENTICATION_HOST,RESTRICTED?,ALLOWED_HOST+)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT DEFAULT_HOST (#PCDATA)>
<!ELEMENT IMAP_BASEDIR (#PCDATA)>
<!ELEMENT AUTHENTICATION_HOST (#PCDATA)>
<!ELEMENT RESTRICTED EMPTY>
<!ELEMENT ALLOWED_HOST (#PCDATA)>

<!ATTLIST GROUP
   name    CDATA #REQUIRED>

<!ATTLIST CONFIG
   type    CDATA #REQUIRED>

<!ATTLIST VIRTUALS
   enabled (true|false) "true">

=== siriusxiv/ubik/src/net/wastl/webmail/data/xml/webmail.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE SYSDATA SYSTEM "%DTDDIR%/sysdata.dtd">
<SYSDATA>
  <VIRTUALS enabled="true"/>
  <DOMAIN>
    <NAME>GCLC</NAME>
    <DEFAULT_HOST>178.170.118.40</DEFAULT_HOST>
    <AUTHENTICATION_HOST>178.170.118.40</AUTHENTICATION_HOST>
    <RESTRICTED/>
    <ALLOWED_HOST>localhost</ALLOWED_HOST>
  </DOMAIN>
</SYSDATA>
