=== siriusxiv/ubik/doc-src/guide.dtd
<!-- DTD for JWebMail Users's Guide -->

<!--
$Id: guide.dtd 140 2008-10-31 21:49:50Z unsaved $

Copyright 2008 by the JWebMail Development Team and Sebastian Schaffert.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

<!ELEMENT GUIDE (TITLE,REVISION,AUTHOR,SECTION+)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT REVISION (#PCDATA)>
<!ELEMENT AUTHOR (#PCDATA)>
<!ELEMENT SECTION (SUBSECTION|P|CONTENTS)*>
<!ELEMENT CONTENTS (#PCDATA)>
<!ELEMENT SUBSECTION (SUBSUBSECTION|P)*>
<!ELEMENT SUBSUBSECTION (P)*>
<!ELEMENT P (#PCDATA|LIST|NLIST|NOTE|TABLE|STRONG|CODE|EM|A|BR)*>
<!ELEMENT LIST (ITEM)*>
<!ELEMENT NLIST (ITEM)*>
<!ELEMENT ITEM (#PCDATA|TABLE|P|STRONG|CODE|EM|A|BR)*>
<!ELEMENT NOTE (#PCDATA|STRONG|CODE|EM|A|BR)*>
<!ELEMENT STRONG (#PCDATA|A|EM)*>
<!ELEMENT EM (#PCDATA|A)*>
<!ELEMENT CODE (#PCDATA|STRONG|EM|A|BR)*>
<!ELEMENT BR (#PCDATA)>
<!ELEMENT A (#PCDATA)>
<!ELEMENT TABLE (TR)*>
<!ELEMENT TR (TD)*>
<!ELEMENT TD (#PCDATA|CODE|EM|STRONG|A)*>

<!-- Sections, Subsections and Subsubsections require a name (the title of the section)
     and a unique ID within the document for referencing -->
<!ATTLIST SECTION       name CDATA #REQUIRED
                        id   CDATA #REQUIRED>
<!ATTLIST SUBSECTION    name CDATA #REQUIRED
                        id   CDATA #REQUIRED>
<!ATTLIST SUBSUBSECTION name CDATA #REQUIRED
                        id   CDATA #REQUIRED>

<!-- Links are very simple here, they just require a reference -->
<!ATTLIST A             href CDATA #REQUIRED>

=== siriusxiv/ubik/doc-src/guide.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>

<!--
$Id: guide.xml 140 2008-10-31 21:49:50Z unsaved $

Copyright 2008 by the JWebMail Development Team and Sebastian Schaffert.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

<!DOCTYPE GUIDE SYSTEM "guide.dtd">

<GUIDE>
  <TITLE>JWebMail v1.0.1*</TITLE>
  <REVISION>$Revision: 140 $</REVISION>
  <AUTHOR>Blaine Simpson, blaine.simpson@admc.com</AUTHOR>
  <SECTION name="Contents" id="contents"><CONTENTS/></SECTION>
  <SECTION name="What is JWebMail" id="about">
    <P>
      JWebMail is a <A href="http://en.wikipedia.org/wiki/Web_mail">web mail</A>
      server.
      Web mail allows an organization to provide a WWW interface for each user
      to his mailbox(es).
      Unlike Yahoo Mail, Hotmail, and Gmail, JWebMail presents a web interface
      to traditional email accounts which you or somebody else provide.
      The target email account servers may be restricted by
      JWebMail.
    </P> <P>
      By virtue of JWebMail being a pure Java appplication, it has excellent
      portability, scalability, and performance.
      We have designed JWebMail so that it works out-of-the-box for a home
      LAN setup by just dropping the .war file into your servlet container
      (which includes all modern application servers).
    </P>
    <SUBSECTION name="Use Cases" id="about:usecases">
      <P>Common use-cases
        <LIST>
          <ITEM>
            Serve JWebMail on the same host that your traditional email
            server runs on, to provide web access in addition to dedicated
            email client access.
          </ITEM>
          <ITEM>
            Run JWebMail to provide members Internet web access to their email
            accounts on an internal mail server.
          </ITEM>
          <ITEM>
            Run a single JWebMail server to allow for a single, unified
            interface to all of the email accounts for your users, whether
            the target email accounts are internal organizational accounts
            and/or external accounts.
          </ITEM>
        </LIST>
      </P>
    </SUBSECTION>

    <SUBSECTION name="Features" id="about:features">
      <P>
        Features include:
        <LIST>
          <ITEM>Product is independent of the target email account
            <EM>provider(s)</EM>.</ITEM>
          <ITEM>Gives a user full access to his/her IMAP mailbox through a simple-to-use WWW interface</ITEM>
          <ITEM>Supports multiple folders on multiple hosts, depending on mail protocol used
            (IMAP supports different folders on the same host, POP doesn't)</ITEM>
          <ITEM>Supports SSL protocols <CODE>imaps</CODE> and <CODE>pop3s</CODE>.</ITEM>
          <ITEM>Sophisticated folder management system</ITEM>
          <ITEM>100% HTML 3.2/4.0 output, no Java on the Client side</ITEM>
          <ITEM>Supports multiple languages, configurable for each user</ITEM>
          <ITEM>Flexible template system to personalize look and feel and write new language files using XML and
            XSL</ITEM>
          <ITEM>Runs as a <EM>web application</EM> in a Java servlet container</ITEM>
          <ITEM>Improved session management keeps mail connections alive</ITEM>
          <ITEM>Performance, scalability, and portability
                of a pure Java application</ITEM>
          <ITEM>Usage of JavaMail-API ensures compatibility to many mail
                standards</ITEM>
          <ITEM>Open Source distribution allows easy customization</ITEM>
          <ITEM>Web-based administration interface</ITEM>
          <ITEM>Support for multiple virtual user domains</ITEM>
          <ITEM>Easily add new features through the JWebMail modular plugin concept
            (support for dependencies, hooking into URLs, etc)</ITEM>
          <ITEM>Application/Data separation allows for redeployments and
            upgrades without losing any configuration or user data.</ITEM>
        </LIST>
      </P>
    </SUBSECTION>
  </SECTION>

  <SECTION name="Installation" id="install">
    <SUBSECTION name="Introduction" id="install:introduction">
      The basic installation instructions here can also be found in plain
      text format in the file INSTALL.txt in the distribution.
    </SUBSECTION>
    <SUBSECTION name="Requirements" id="install:requirements">
      <P>For running JWebMail you need the following software:
        <LIST>
          <ITEM>
            A mailserver for sending (SMTP) and receiving (IMAP) mails; by default,
            JWebMail will use <CODE>localhost</CODE> for both
          </ITEM> <ITEM>
            A Java servlet container which supports the 2.4 servlet spec,
            and runs on a Java 1.5 or greater JVM (either JRE or JDK).
            Anything from a stripped down servlet-container
            like <A href="http://tomcat.apache.org/">Tomcat</A>,
            to a J2EE application server like
            <A href="http://www.jboss.org/jbossas">JBoss</A> or
            <A href="http://www.ibm.com/software/webservers/appserv/was/">
              WebSphere</A> will work.
          </ITEM> <ITEM>
            Your servlet container needs modern versions of the following libraries
            installed:
            <LIST>
              <ITEM>
                JavaMail API (typically <CODE>mailapi-*.jar</CODE>)
                You can download
                <A href="http://pub.admc.com/lib-repos/mailapi-1.4.1.jar">
                   version 1.4.1 of the JavaMail API library here</A>.
              </ITEM> <ITEM>
                JavaMail SMTP provider (typically <CODE>smtp-*.jar</CODE>).
                You can download
                <A href="http://pub.admc.com/lib-repos/smtp-1.4.1.jar">
                  version 1.4.1 of the SMTP library here</A>.
              </ITEM> <ITEM>
                JAF/Java Activation Framework
                (<EM>not necessary if your servlet container uses Java 1.6</EM>,
                since Java 1.6 includes the activation framework).
                Java 1.5-users can download
                <A href="http://pub.admc.com/lib-repos/jaf-1.1.1.jar">
                version 1.1.1 of JAF library here</A>.
              </ITEM>
            </LIST>
          </ITEM>
        </LIST>
      </P> <P>
        If you wish to build a custom app, or develop, you will also need a
        standalone Java JDK 1.5 or later, and Ant 1.7 or later, as described below.
        Any or no Java IDE will work.
      </P>
    </SUBSECTION>
    <SUBSECTION name="Installing" id="install:intro">
      <P>
        There are separate sections below, depending on whether you want to
        just <EM>run</EM> JWebMail, or to build it on the command-line or
        with an IDE.
      </P>
    <SUBSUBSECTION name="Installing Application (binary install)"
                id="install:binary">
      <P>
        This is the preferred installation method if you just want to run
        JWebMail, and have no need to customize the application iteself.
      </P> <P>
        This installation is very simple:
      </P> <P>
        Install <CODE>jwebmail.war</CODE> as you would install any War file.
      </P> <P>
        With Tomcat, the easiest way is to use the Manager webapp, which serves
        http://localhost:8080/manager/html by default.  Log in and deploy the
        war using the Gui (you can see or add manager accounts in the file
        $CATALINA_BASE/config/tomcat-users.xml).
      </P> <P>
        For every application server that I know of, if you have auto-deploy on
        (usually the default mode) you can become the app-server <EM>owner</EM> (the
        account under which the server process(es) run), and just copy the war
        file into the webapp landing directory.  If you don't have access to that
        account, see your app server docs, because the war file permission
        requirements vary (if you have superuser privileges, you can always
        change the file to be owned by the app-server owner).  Rest assured,
        your app server has several easy ways to deploy war files.
      </P> <P>
        JWebMail is then available by visiting http://yourhost:PORT/jwebmail
        with a web browser.
      </P> <P>
        Please don't forget to visit the administration interface first. You can access
        it by browsing http://yourhost:PORT/jwebmail/admin.  Initial password
        is <CODE>Secret</CODE>.
      </P>
    </SUBSUBSECTION>
    <SUBSUBSECTION name="Build and Install from source" id="install:build">
      <P>
        JWebMail is compiled by using the Ant build-system.  You will need
        <A href="http://ant.apache.org/">Ant</A> version 1.7 or greater and
        <A href="http://java.sun.com/javase/">Java JDK 1.5 or greater</A>
        to build JWebMail.
      </P> <P>
        You can obtain the JWebMail source code by extracing a source code
        distribution package, or by exporting or checking out our code from
        SourceForge.  You can get our distro packages at 
        <A href="https://sourceforge.net/project/showfiles.php?group_id=2056">
        https://sourceforge.net/project/showfiles.php?group_id=2056</A>.
        You can use any Subversion client to get our trunk code from
        <CODE>https://jwebmail.svn.sourceforge.net/svnroot/jwebmail/trunk</CODE>.
      </P> <P>
        The following steps are required (for a quick-start):<NLIST>
          <ITEM>
            Set your JAVA_HOME environment variable (to the directory where the JDK is
